hmcts/ccpay-payment-app

pom.xml
https://github.com/FasterXML/jackson-databind/issues/1931
=> Fixed latest cve error for jackson-data-bind CVE-2018-7489.

dependency-check-suppressions.xml
This is due to ff4j dependencies added recently to payment-app.  
**Apache Standard Taglibs before 1.2.3 allows remote attackers to execute arbitrary code or conduct external XML entity (XXE) attacks via a crafted XSLT extension in a (1) <x:parse> or (2) <x:transform> JSTL XML tag**
But we are using latest version 1.2.5 .
`  +--- org.ff4j:ff4j-web:1.7.1
|    +---  #org.apache.taglibs:taglibs-standard-impl:1.2.5`
Need some investigation to find out the actual cause.
=> added to suppression file temporarily

api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/FeeDto.java, api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/FeeDtoTest.java, api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/PaymentDtoTest.java, api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/CardPaymentDtoMapper.java, api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/CreditAccountDtoMapper.java
…LOAT_AS_INT flag). This causes volume value truncate to integer (eg: from 1.5 to 1) and not throwing validation error.
=> Fee volume float value truncate fix

api/src/main/resources/bootstrap.yaml
Changing to property instead of env variable as env variables take precedence while using relaxed binding for spring properties.
https://tools.hmcts.net/jira/browse/RPE-1009
Changing to property instead of env variable as env variables take precedence while using relaxed binding for spring properties.
```
[ ] Yes
[x] No
```
=> changing to property instead of env variable

Dockerfile
curl is not part of the image anymore that result to a status "unhealthy" for the container.
I replaced it with wget from the spring-boot-template.
```
[ ] Yes
[ ] No
```
=> fix docker health check

api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java, api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PbaControllerTest.java
https://tools.hmcts.net/jira/browse/PAY-1695
https://tools.hmcts.net/jira/browse/PAY-1696
Added net_amount to feeDTO. If net_amount is not null for fee for a payment, then GET endpoint for payments will use net amount for the calculated amount.
```
[x ] Yes
[ ] No
```
=> Pay 1695 Pay 1696

api/build.gradle, api/liquibase.gradle, api/src/main/java/uk/gov/hmcts/PaymentApiApplication.java
This is based on hmcts/liquibase#2
Idea is to move everyone over to flyway. This is temporary fix to resolve locking issues causing multiple failures in PRs and Demo especially. 
```
[ ] Yes
[x] No
```
=> Moving to hmcts version of liquibase which performs better DB locking

api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/service/IdempotencyService.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/service/IdempotencyServiceImpl.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java, api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java, api/src/test/java/uk/gov/hmcts/payment/api/domain/service/IdempotencyServiceImplTest.java
https://tools.hmcts.net/jira/browse/PAY-6779
Allow retry on failed liberata calls, specifically responses which come back as HTTP 504, 412 and 402.
=> PAY-6779: Allow retry on failed PBA Liberata calls

api/build.gradle, api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java, api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/ServiceRequestProviderTest.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java, api/src/main/java/uk/gov/hmcts/payment/api/dto/OnlineCardPaymentResponse.java, codecov.yml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-5998
Some contracts in the pact broker are no longer being verified.
For consumer probate_caveatsFrontEnd and provider payment_cardPayment there are two null pointer issues that probably started happening after the Java 17 upgrade, that brought with it Spring Boot and Mockito upgrades.
Specifically for Mockito at some point the keyword 'any' stopped matching null https://github.com/mockito/mockito/issues/1188 
Issue 1: Mock statement not operating in CardPaymentProviderTest.
Whereas previously a null was passed in (possibly unintentionally), and it was accepted by 'any', the paymentFeeLinkRepositoryMock would still return an instance of PaymentFeeLink. Under the stricter conditions of the new Mockito however this failure of null to match the …
=> PAY-5998 fix pact verification failures

api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java, api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java, api/src/test/java/uk/gov/hmcts/payment/api/mapper/PaymentDtoMapperTest.java, api/src/test/java/uk/gov/hmcts/payment/api/unit/SendMessageApplication.java
https://tools.hmcts.net/jira/browse/PAY-6943
Update to the /card-payments/{reference} endpoint to also use the reference ("RC" number) when determining the payments from the payment_link_id value which isn't unique if there are multiple payment attempts.
=> PAY-6943: Change to pull back card payment based on reference

api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java, api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentGroupDtoMapper.java
https://tools.hmcts.net/jira/browse/PAY-6479
remove check for payments role in paymentgroups, so that users without payments role still have access to payments so that the total fees left to pay calculation works both with and without the payments role.
=> Pay 6479 remove payments role from payment groups

api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/PayFeeLinkRepositoryStub.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/CreditAccountPaymentController.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentGroupController.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentRecordController.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentReference.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/RemissionController.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/mapper/ServiceRequestDtoDomainMapper.java, api/src/main/resources/application-local.properties, api/src/main/resources/db/changelog/db.changelog-0.1.13.yaml, api/src/main/resources/db/changelog/db.changelog-master.xml, api/src/test/java/uk/gov/hmcts/payment/api/mapper/ServiceRequestDtoDomainMapperTest.java, charts/payment-api/Chart.yaml, model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentFeeLinkRepository.java
https://tools.hmcts.net/jira/browse/PAY-7137
Turn service request payment reference into a sequence. 
This is required so when multiple service requests come in at the same time, the old date based creation of the service request number based on milliseconds from epoch was generating the same service-request number. With the based on a sequence, this will never happen.
The format of the number hasn't changed. It's still based on the the same format as before with the first number being the current year and the second number now being based off the sequence payment_reference_seq.
YYYY-nnnnnnnnnnnnn
I.e. 2024-1750000000163
This should not have any impact on external or internals services and should gaurentee that each Service Request has a unique payment reference.
The sequence starts from …
=> PAY-7137: Make Payment Reference -Unique

api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentController.java, api/src/main/java/uk/gov/hmcts/payment/api/service/IacService.java, api/src/main/java/uk/gov/hmcts/payment/api/service/IacServiceImpl.java, api/src/test/java/uk/gov/hmcts/payment/api/service/IacServiceTest.java, build.gradle
https://tools.hmcts.net/jira/browse/PAY-7310
This code update hooks of the back of the IAC Supplimentary data collection for IAC Reconciliation Reports and adds a search to identify the Case Reference from the PaymentFeeLink record should one not be provided in the payment record.
The seach looks for a PaymentFeeLink against the case, there might be multiple PaymentFeeLink records, so the first one found with a Case Reference string is used for the Reconciliation Report. It's impossible for a case to have more than one Case Reference, so this should be a safe change.
Extensive tests performed in the IacServiceTest class. Multiple PaymentFeeLink records have been tested against a case. Also tested cases with an existing Case Reference which shouldn't change. The IacService is only invoked …
=> PAY-7310: Update to fix IAC Issue

api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java, api/src/main/java/uk/gov/hmcts/payment/api/service/IacServiceImpl.java, api/src/test/java/uk/gov/hmcts/payment/api/service/IacServiceTest.java
https://tools.hmcts.net/jira/browse/PAY-7310
This code update hooks of the back of the IAC Supplimentary data collection for IAC Reconciliation Reports and adds a search to identify the Case Reference from the PaymentFeeLink record should one not be provided in the payment record.
The search looks for a PaymentFeeLink against the case using the Payment Group (Service Request) which should be unique across a case. If a Case Reference was found in the PaymentFeeLink and it was missing in the Payment record, then it gets used in the IAC Reconciliation Report.
Please note for this to work, it has to be an IAC case and the payment has to be made from a Payment Group (Service Request) which has a populated Case Reference. Currently only Service Requests created from CCD have a Case Reference …
=> PAY-7310: Update to identify Case Reference by Payment Group

api/build.gradle, api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java, api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTestConfiguration.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/CreditAccountPaymentController.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentReference.java
https://tools.hmcts.net/jira/browse/PAY-7213
Some subtle changes around the use of PaymentReference over the last 8 months broke the contract tests because it was turning up as a null in the mock environment. These changes make it available as a bean. Also removing the setting of publishResults to true, because this very likely having the opposite effect. Other projects that succesfully publish their results do not use this, and our results havn't been published for 8 months, which is how we have missed the error with PaymentReference.
Contract tests now working. Not all of them, but it's an improvement.
=> Pay 7213 pact contract verification

api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/ServiceRequestProviderTest.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainService.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java, api/src/main/resources/application.properties, api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java, api/src/test/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceTest.java, model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentStatus.java
https://tools.hmcts.net/jira/browse/PAY-7443
The Civil CUI Release 2 had an issue with session's expiring which caused duplicate payments to be pushed through multiple times. 
To prevent this from happing from a Fee and Payment perspective, this endpoint is being updated to provide an additional check for a valid payment. If a valid payment is found, the user is returned to the application they came from via the return URL, instead of being sent through to the GovPay card payment process.
_/card-payments/{internal-reference}/card-payments_
After the business validation has been completed, a new check has been included _hasOnlineCardPaymentAlreadySuccess_ which performs if true returns the user to the supplied 'return-url'. The checks are as follows.
A. Find the first existing payment in …
=> PAY-7443: Service Request Online Card Duplicate Payment Update

api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java, api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTestConfiguration.java, api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
See [PAY-7474](https://tools.hmcts.net/jira/browse/PAY-7474)
This contract test was failing with a null pointer exception since the introduction of PaymentReference.
This fix sets up the mock and passes it into the constructor.
Works locally and also on pact broker.
=> PAY-7474 fix contract test for probate_caveatsFrontEnd

api/src/main/java/uk/gov/hmcts/payment/api/controllers/MaintenanceJobsController.java, api/src/test/java/uk/gov/hmcts/payment/api/componenttests/jobs/MaintenanceJobsControllerMockTest.java
https://tools.hmcts.net/jira/browse/PAY-7556
Wrap delegatingPaymentService.retrieveWithCallBack(reference.getReference()) request in try catch as a rogue payment status was causing an error when retrieving the payment from GovPay.
Tests have been updated, and the outcome in the environments will be observed. Current process in Prod is broken due to the rogue payment being inaccessible with a 401 error and causing the job process to crash.
=> PAY-7556: Update Payment Status Job for Robustness When Collecting Payment

api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/PaymentDto.java, api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/PaymentDtoTest.java, api/src/main/java/uk/gov/hmcts/payment/api/domain/mapper/ServiceRequestDtoDomainMapper.java, api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java, api/src/main/resources/db/changelog/db.changelog-0.1.15.yaml, api/src/main/resources/db/changelog/db.changelog-master.xml, api/src/test/java/uk/gov/hmcts/payment/api/domain/mapper/ServiceRequestDtoDomainMapperTest.java
https://tools.hmcts.net/jira/browse/PAY-7625
Missing volume in CSV generation. The value is defaulted at a DB level, so doesn't cause an issue in the code.
26/02/2025 I've done a second commit as on further investigation Divorce were creating SRs with an explicit null value for the volume, therefore ignoring the volume default value of 1 in the fee table. I've updated the code to select 1 as the default from the FeeDto object and rerun the SQL to update null volume values to 1 on top of the original change to correct the CSV to make it more robust when picking up possible null values.
Unit test updated, manual reconciliation report run.
=> PAY-7625: Updated to default volume in CSV generation

api/build.gradle, model/build.gradle
https://tools.hmcts.net/jira/browse/PAY-7686
Payment App - DTSPO-24952: Looks like the HMCTS java-logging library 6.1.8 not available, reverted back to 6.1.7 which is still accessible. Can be corrected once  DTSPO-24952 has been resolved.
Blocking FT, once these pass and application logging can be confirmed, that should be enough.
=> Reverting java-logging as library has gone AWOL

api/build.gradle, api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java, api/src/main/java/uk/gov/hmcts/payment/api/servicebus/TopicClientProxy.java, api/src/test/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceTest.java, api/src/test/java/uk/gov/hmcts/payment/api/mapper/PBAStatusErrorMapperTest.java, api/src/test/java/uk/gov/hmcts/payment/api/service/IacServiceTest.java, api/src/test/java/uk/gov/hmcts/payment/api/service/RefundRemissionEnableServiceTest.java, api/src/test/java/uk/gov/hmcts/payment/api/servicebus/TopicClientProxyTest.java, api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, cve-resolution-strategy.gradle, gov-pay-client/build.gradle, model/build.gradle, model/src/test/java/uk/gov/hmcts/payment/api/model/CheckDigitTest.java
https://tools.hmcts.net/jira/browse/PAY-8047
For Ways2Pay PBA payments, the apportionment update was carried out after a ServiceBus call to update services with the payment status. On rare occasions however the SB call would fail, meaning the apportionment table wouldn't be updated.
This update moves the apportionment code to before the Servicebus call and adds extra logging around the SB call to diagnose issues the send message process which can appear to hang the SB is unavailable. If an exception get's raised then it will attempt a retry. 
Observed in Demo
=> PAY-8047: PBA: Move Apportionment before ServiceBus + extra logging

api/src/main/resources/db/changelog/db.changelog-0.1.16.yaml, api/src/main/resources/db/changelog/db.changelog-master.xml, charts/payment-api/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-8065
Volume defaults to 1, but older fee records are still showing null values which causes issues when refunding.
Functional tests and manual testing, also this was covered extensively in PAY-7625.
=> PAY-8065: Updating volume to be 1 if null
