- App_Data/jobs/triggered/csv-report/run.sh
will split into relevant jobs very soon.
> updated to inline with api changes.

- api/src/main/resources/application-production-slot.properties
- api/src/main/resources/application-staging-slot.properties
- api/src/main/resources/application.properties
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/variables.tf
Reverts hmcts/ccpay-payment-app#228
> Revert "[PREVIEW] liquibase run on staging slot only."

- infrastructure/aat.tfvars
> ROC-4254 Switch to SIDAM

- infrastructure/aat.tfvars
Reverts hmcts/ccpay-payment-app#259
> Back to TIDAM

- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRecordControllerTest.java
No testing required just merge it.
> PAY-1229: Testing ReportedDateOffline is returned by /payments

- infrastructure/variables.tf
set liquibase back to the disabled state once current deployment is success https://build.platform.hmcts.net/job/HMCTS_Fees_and_Pay/job/ccpay-payment-app/job/master/39/
> disabled liquibase

- infrastructure/aat.tfvars
This reverts commit 69ea62f2bbfc090cdfeb0bfb47caa567f9392d70.
> Revert "Point to SIDAM"

- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
- build.gradle
- docker-compose.yml
- infrastructure/main.tf
- kubernetes/config.aat.yaml
> update jui app as trusted app

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/security/SpringSecurityConfiguration.java
added wild card to spring security
> added wild card to spring security

- infrastructure/aat.tfvars
- kubernetes/config.aat.yaml
> Update aat.tfvars to make it consistent with prod

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
> fixed pba finrem test as flag is disabled

- Jenkinsfile_parameterized
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/AccountFunctionalTest.java
> Idam build fix

- infrastructure/saat.tfvars
> fixed saat idam whitelist fix

- Jenkinsfile_parameterized
> added required gov_pay key for functional tests

- api/src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/PAY-1469
Enabling FINREM check against Liberata by default
```
[x ] Yes
[ ] No
```
> feature.credit.account.payment.liberata.check enabled by default

- api/src/main/resources/bootstrap.yaml
- build.gradle
- charts/payment-api/Chart.yaml
- charts/payment-api/requirements.yaml
- charts/payment-api/values.template.yaml
Making postgress conditional
Upgrading java chart
Adding secret for DB password
https://tools.hmcts.net/jira/browse/RPE-1009
Making postgress conditional
Upgrading java chart
Adding secret for DB password
```
[ ] Yes
[x] No
```
> Changes to be able to deploy in AAT using Flux

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
Changing one functional test to reflect changes after making FINREM liberata check on by default
```
[ ] Yes
[ x] No
```
> changing functional test to reflect new changes

- infrastructure/variables.tf
Enabling liberata check for FINREM
```
[ x] Yes
[ ] No
```
> turning feature_credit_account_payment_liberata_check on by default

- api/src/main/resources/application.properties
- infrastructure/aat.tfvars
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/PciPalPaymentServiceTest.java
> Removed pcipal redirect url and aat sidam switch

- .gitignore
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- model/src/main/java/uk/gov/hmcts/payment/api/dto/PciPalPaymentRequest.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/PciPalPaymentServiceTest.java
https://tools.hmcts.net/jira/browse/PAY-1654
PCIPal changes
```
[x] Yes
[ ] No
```
> fix for pciPal

- dependency-check-suppressions.xml
Spring Security contains an authorization bypass when using method security
https://nvd.nist.gov/vuln/detail/CVE-2018-1258
> CVE-2018-1258 - suppression

- dependency-check-suppressions.xml
CVE-2018-1258 supression
```
[ ] Yes
[ x] No
```
> CVE-2018-1258 supression

- docker-compose.yml
dockercompose : added missing config prop ASB_CONNECTION_STRING
```
[ ] Yes
[x ] No
```
> adding missing config prop ASB_CONNECTION_STRING

- api/src/main/resources/logback-includes.xml
fixing logback upgrade issue
```
[ ] Yes
[x ] No
```
> fixing logback upgrade issue

- infrastructure/demo.tfvars
> Payment demo pointing to aat idam

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/util/PaymentsDataUtil.java
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-1690
retrieve payment by reference
```
[ ] Yes
[ x] No
```
> GET endpoint payment by reference

- infrastructure/demo.tfvars
sidam demo
```
[ ] Yes
[x ] No
```
> pay demo => sidam demo

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
Using known SiteID for functional tests concerning BAR payments
```
[ ] Yes
[x ] No
```
> using known siteID for the bar payment

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
> added pcipal thumb prints

- api/src/main/java/uk/gov/hmcts/PaymentApiApplication.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRecordControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/ReferenceDataControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/RemissionControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/unit/FeeCacheTest.java
- infrastructure/prod.tfvars
- model/src/main/java/uk/gov/hmcts/payment/api/service/ReferenceDataServiceImpl.java
- reference-data/src/main/java/uk/gov/hmcts/payment/referencedata/controllers/ReferenceDataController.java
- reference-data/src/main/java/uk/gov/hmcts/payment/referencedata/service/SiteService.java
- reference-data/src/main/java/uk/gov/hmcts/payment/referencedata/service/SiteServiceImpl.java
> PAY-1659 Removed the duplicate pci pal callback url

- api/build.gradle
- api/src/main/java/uk/gov/hmcts/PaymentApiApplication.java
- api/src/main/resources/application.properties
- gov-pay-client/build.gradle
- gov-pay-client/src/main/java/uk/gov/hmcts/payment/api/external/client/GovPayClient.java
- model/build.gradle
- model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-1578
circuit breaker config
```
[ ] Yes
[ x] No
```
>  added basic circuit breaker config. Still need to tune values

- build.gradle
- charts/payment-api/values.preview.template.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/MockAccountServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-1754
```
[ ] Yes
[x ] No
```
> added mock for liberata response (Account service)

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/MaintenanceJobsController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/jobs/MaintenanceJobsControllerMockTest.java
- api/src/test/resources/application-componenttest.properties
- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/DelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingCardPaymentLinkServiceTest.java
https://tools.hmcts.net/jira/browse/PAY-1738
serviceCallbackUrl bug fix
```
[ ] Yes
[x ] No
```
> PAY-1738 - service callback fix

- gov-pay-client/src/main/java/uk/gov/hmcts/payment/api/external/client/GovPayClient.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
hystrix timeout setting
```
[ ] Yes
[x ] No
```
> disabled hystrix timeout

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/configuration/FF4jConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CreditAccountPaymentController.java
- api/src/main/java/uk/gov/hmcts/payment/api/validators/DuplicatePaymentValidator.java
- api/src/main/resources/application.properties
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CreditAccountPaymentControllerTest.java
- dependency-check-suppressions.xml
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingCreditAccountPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/v1/model/exceptions/DuplicatePaymentException.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingCreditAccountPaymentServiceTest.java
https://tools.hmcts.net/jira/browse/PAY-1723
Tactical solution to check for duplicates and warn the users
```
[ ] Yes
[x ] No
```
> Reject duplicate pba payment

- api/build.gradle
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CallBackServiceFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/config/TestConfigProperties.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/dsl/PaymentsTestDsl.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/java/uk/gov/hmcts/payment/api/configuration/security/SpringSecurityConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/mock/MockCallbackControllerForTesting.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
- api/src/main/resources/application.properties
- build.gradle
- charts/payment-api/values.preview.template.yaml
- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/variables.tf
- model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/MockAccountServiceImpl.java
Reverts hmcts/ccpay-payment-app#462
> Revert "Revert "callback functional tests ""

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentRecordFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentRecordDtoMapper.java
> Payment fee reference functional verification test

- README.md
- build.gradle
https://tools.hmcts.net/jira/browse/PAY-1813
Upgrading the spring boot version to latest
```
[ ] Yes
[x] No
```
> upgrade spring boot

- infrastructure/prod.tfvars
> Check for duplicate payment in prod

- model/src/main/java/uk/gov/hmcts/payment/api/util/PayStatusToPayHubStatus.java
> PAY-1847 Added new payhub status decline

- infrastructure/variables.tf
> remove https

- infrastructure/prod.tfvars
> PAY-1922 Amended ccd prod url to http

- model/src/main/java/uk/gov/hmcts/payment/api/service/CcdDataStoreClientServiceImpl.java
added a comment
```
[ ] Yes
[ ] No
```
> Added a comment

- build.gradle
- infrastructure/demo.tfvars
> PAY-1922 Excluded the default health check class from ccd jar

- infrastructure/main.tf
> PAY-1922 Added a temp env variable

- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/TelephonyControllerTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/util/PayStatusToPayHubStatus.java
> PAY-1870 Payment status mapping updated from decline to declined

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentGroupFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/dsl/PaymentsTestDsl.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentGroupController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentGroupDto.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CaseControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentGroupControllerTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/v1/model/exceptions/InvalidFeeRequestException.java
> PAY-1934 -> adding validation and changing into payment group

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/FF4jConfiguration.java
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
Add a feature flag with default disabled to be able to switch case id check with ccd
```
[ ] Yes
[X] No
```
> [AK] Add case id validation feature flag

- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentGroupDtoMapper.java
https://tools.hmcts.net/jira/browse/PAY-1985
```
[ ] Yes
[X] No
```
> PAY-1985 -> Date created is added to the paymentresponse

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/CardPaymentRequest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CMCCardPaymentFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentGroupController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentGroupControllerTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/audit/AppInsightsAuditRepository.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/DelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/LoggingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentService.java
> PAY-1983 -> card payments inside payment group

- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/RemissionControllerTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/RemissionService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/RemissionServiceImpl.java
> Net Amount issue in partial remission

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-2018
added the suppression for 
<suppress>
<cve>CVE-2019-12814</cve>
<cve>CVE-2019-14379</cve>
<cve>CVE-2019-14439</cve>
</suppress>
```
[ ] Yes
[x ] No
```
> PAY-2018 added suppresion for CVV

- .gitignore
- Dockerfile
- api/src/main/resources/logback-includes.xml
> [AK] Update helm chart

- Jenkinsfile_CNP
NA
Build failure fix for Vault changes.
```
[ ] Yes
[x ] No
```
> Vault changes - Build failure fix.

- build.gradle
Web job fix for adding files manually
```
[ ] Yes
[x ] No
```
> Web job fix for adding files manually

- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-2091
Telephony Payments success status is not storing in status_history table   
```
[ ] Yes
[x ] No
```
> Code changes for adding value in status-history table.

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/idam/IdamService.java
- api/src/functionalTest/resources/application-functional-tests.properties
> Functional Test Fix

- api/src/main/resources/application.properties
Updating to true to include CCD validation
```
[ ] Yes
[ x] No
```
> Updating to true to include CCD validation

- charts/payment-api/Chart.yaml
- charts/payment-api/requirements.yaml
- charts/payment-api/values.yaml
> RDM-5918- added image url in chart values

- api/build.gradle
- dependency-check-suppressions.xml
No Ticket
Upgrading library versions
```
[ ] Yes
[x] No
```
> Updating jackson library

- api/build.gradle
- dependency-check-suppressions.xml
No Ticket
Adding jackson library vulnerabilities into supperssion file
```
[ ] Yes
[x] No
```
> Adding jackson library vulnerabilities into supperssion file

- dependency-check-suppressions.xml
- infrastructure/main.tf
Updating module names from moj to cnp
```
[ ] Yes
[x] No
```
> Updating to cnp modules from moj modules

- api/src/main/resources/application.properties
- charts/payment-api/values.yaml
https://tools.hmcts.net/jira/browse/ROC-6115
We are moving some logic from our frontend (s2s: cmc) to backend (s2s: cmc_claim_store). We will remove cmc later.
```
[ ] Yes
[x] No
```
> CMC: enable cmc_claim_store

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/security/SpringSecurityConfiguration.java
- api/src/main/resources/application.properties
- charts/payment-api/values.yaml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-2234
Adding xui to trusted services
```
[ ] Yes
[x] No
```
> Adding XUI service name to trusted services

- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
> corrected the env variable

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> updated the URL

- charts/payment-api/requirements.yaml
> upgraded Java version

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> added secrete

- charts/payment-api/Chart.yaml
- charts/payment-api/requirements.yaml
> Bumping chart versions

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/PaymentAllocationDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentAllocationController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
- api/src/main/resources/db/changelog/db.changelog-0.1.3.yaml
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentAllocationControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/util/PaymentsDataUtil.java
- model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentAllocation.java
PAY-2285: New Data Capture fields added for shortfall/surplus
PAY-2285: New Data Capture fields added for shortfall/surplus
```
[ ] Yes
[ x] No
```
> PAY-2285: New Data Capture fields added for shortfall/surplus

- .travis.yml
- api/src/main/resources/application.properties
- api/src/main/resources/bootstrap.yaml
- charts/payment-api/Chart.yaml
- charts/payment-api/values.aat.template.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
> PAY-2419:Payment AKS Migration

- charts/payment-api/values.yaml
> Added Aad identity name

- charts/payment-api/Chart.yaml
> Bump up the chart version

- charts/payment-api/Chart.yaml
- charts/payment-api/values.aat.template.yaml
- charts/payment-api/values.yaml
> PAY-2419:AKS changes for payment

- charts/payment-api/values.aat.template.yaml
> Added identity name to aat template explictly

- Jenkinsfile_CNP
> Legacy Deployment enable on AAT

- Jenkinsfile_CNP
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/PAY-2612
Hemp upgrade changes
```
[ ] Yes
[x] No
```
> Hemp upgrade changes

- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
> APPInsights key updates

- Jenkinsfile_nightly
- api/src/main/java/uk/gov/hmcts/PaymentApiApplication.java
Adding Nightly Build file.
```
[ ] Yes
[x] No
```
> PAY-Knightly

- infrastructure/main.tf
> PAY-2419:Rectified the missing bits

- infrastructure/main.tf
> PAY-2419:Create resource

- Jenkinsfile_nightly
- audit.json
> PAY-2675:Enable Security Scan

- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentGroupDtoMapper.java
PAY-2687 : Payment API to send Date Updated as a part of payment data
PAY-2687 : Payment API to send Date Updated as a part of payment data
```
[ ] Yes
[X ] No
```
> PAY-2687 : Payment API to send Date Updated as a part of payment data

- Jenkinsfile_CNP
Enable ASE Deployment
Enable ASE Deployment
```
[ ] Yes
[ X] No
```
> PAY-2687 : Enable AAT deployment in ASE.

- dependency-check-suppressions.xml
PAY-2687 : Dependency suppression.
PAY-2687 : Dependency suppression.
```
[ ] Yes
[ X] No
```
> PAY-2687 : Dependency suppression.

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
ProdRelease22012020
ProdRelease22012020
```
[ ] Yes
[x ] No
```
> Prod release22012020

- dependency-check-suppressions.xml
NA
Suppressions added for build failure.
```
[ ] Yes
[x ] No
```
> Suppressions added for build failure.

- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
PAY-2785 : PCI Call back - success status to be updated once
PAY-2785 : PCI Call back - success status to be updated once
```
[ ] Yes
[ x] No
```
> PAY-2785 : PCI Call back - success status to be updated once

- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
PAY-2789 : FPLA Service Whitelisting (PBA)
PAY-2789 : FPLA Service Whitelisting (PBA)
```
[ ] Yes
[x ] No
```
> PAY-2789 : FPLA Service Whitelisting (PBA)

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/CardPaymentRequest.java
- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/util/Language.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/resources/gov-pay-responses/create-payment-response-welsh-language.json
- dependency-check-suppressions.xml
- infrastructure/main.tf
- model/src/test/java/uk/gov/hmcts/payment/api/v1/model/govpay/GovPayPaymentServiceTest.java
https://tools.hmcts.net/jira/browse/PAY-2746
Gov pay whales analysis
```
[ ] Yes
[x ] No
```
> Gov pay whales analysis

- charts/payment-api/values.yaml
- docker-compose.yml
- infrastructure/main.tf
Pay 2789 fpla whitelisting
Pay 2789 fpla whitelisting
```
[ ] Yes
[ x] No
```
> Pay 2789 fpla whitelisting

- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
PAY-2785 : PCI Call back - Custom AppInsight Event created for Duplicate Success Status update from PCI PAL 
PAY-2785 : PCI Call back - Custom AppInsight Event created for Duplicate Success Status update from PCI PAL 
```
[ ] Yes
[ x] No
```
> PAY-2785 : PCI Call back - Custom AppInsight Event created

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/CardPaymentRequest.java
- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/util/Language.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/main/java/uk/gov/hmcts/payment/api/v1/controllers/PaymentOldController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/resources/gov-pay-responses/create-payment-response-welsh-language.json
- dependency-check-suppressions.xml
- gov-pay-client/src/main/java/uk/gov/hmcts/payment/api/external/client/GovPayClient.java
- gov-pay-client/src/main/java/uk/gov/hmcts/payment/api/external/client/dto/CreatePaymentRequest.java
- gov-pay-client/src/test/java/uk/gov/hmcts/payment/api/external/client/GovPayClientTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentServiceRequest.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/v1/model/LoggingOldPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/v1/model/PaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/v1/model/UserAwareDelegatingOldPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/v1/model/govpay/GovPayPaymentService.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/LoggingPaymentServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/v1/model/LoggingOldPaymentServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/v1/model/UserAwareDelegatingPaymentServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/v1/model/govpay/GovPayPaymentServiceTest.java
> PAY-2760:Welsh language changes for Fees&Pay

- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/TelephonyControllerTest.java
- audit.json
> PAY-2866:Nightly Build pipeline fixes

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/FF4jConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/resources/application-componenttest.properties
- model/src/main/java/uk/gov/hmcts/payment/api/service/DelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/LoggingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentService.java
Pay 2601 payment cancellation api
Pay 2601 payment cancellation api
```
[ ] Yes
[ x] No
```
> Pay 2601 payment cancellation api

- infrastructure/main.tf
PAY-2601 : Configuration Changes
PAY-2601 : Configuration Changes
```
[ ] Yes
[ x] No
```
> PAY-2601 : Configuration Changes

- infrastructure/ithc.tfvars
PAY-2601 : IDAM API url changed for ITHC
PAY-2601 : IDAM API url changed for ITHC
```
[ ] Yes
[ x] No
```
> PAY-2601 : IDAM API url changed for ITHC

- infrastructure/ithc.tfvars
PAY 2601 : Refactor IDAM Url
PAY 2601 : Refactor IDAM Url
```
[ ] Yes
[x ] No
```
> PAY 2601 : Refactor IDAM Url

- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/CreditAccountDtoMapper.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentGroupDtoMapper.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CreditAccountPaymentControllerTest.java
> PAY-2856:PBA missing details backend changes

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/pcipal/TelephonyController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/TelephonyControllerTest.java
- dependency-check-suppressions.xml
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
PAY 2785 : PCIPAL Callback changes
PAY 2785 : PCIPAL Callback changes
```
[ ] Yes
[ x] No
```
> PAY 2785 : PCIPAL Callback changes

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CMCCardPaymentFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/configuration/FF4jConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/resources/application-componenttest.properties
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
- model/src/main/java/uk/gov/hmcts/payment/api/service/DelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/LoggingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentService.java
PAY-2601 : Cancellation API Changes.
PAY-2601 : Cancellation API Changes.
```
[ ] Yes
[ x] No
```
> PAY-2601 : Cancellation API Changes.

- dependency-check-suppressions.xml
CVE Issues Fixed
CVE Issues Fixed
```
[ ] Yes
[ x] No
```
> CVE Issues Fixed

- dependency-check-suppressions.xml
> CVE Suppressed for the Current Release

- Jenkinsfile_CNP
AB#846
Switching demo to AKS
```
[ ] Yes
[x] No
```
> Disabled legacy deployment on Demo

- Jenkinsfile_CNP
AB#846
Switch to AKS on AAT
```
[ ] Yes
[x] No
```
> Disabled legacy deployment on AAT

- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
> Pay-2865-publish chart

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
AB#846
Added missing variable.
```
[ ] Yes
[x] No
```
> Added missing env variable

- Jenkinsfile_CNP
AB#846
Swap DNS to AKS on production.
```
[ ] Yes
[x] No
```
> Swapped_Prod_toAks

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/perftest.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sprod.tfvars
- infrastructure/state.tf
- infrastructure/variables.tf
AB#846
Revert ASE cleanup due to missing webjobs.
```
[ ] Yes
[x] No
```
> Revert "Removed ASE infrastructure"

- Jenkinsfile_CNP
> work around fees and pay deployment

- Jenkinsfile_CNP
Reverts hmcts/ccpay-payment-app#679
> Revert "work around fees and pay deployment"

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> PAY-3217: Updated the chart version as well

- dependency-check-suppressions.xml
> PAY-3217: Suppression of CVEs for timebeing

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
OIDC audience list updated.
```
[ ] Yes
[ x] No
```
> OIDC audience list updated.

- Jenkinsfile_CNP
- api/src/main/resources/bootstrap.yaml
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
> Pay 3268 pt

- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
- docker-compose.yml
> chart version publish for IAC on boarding

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/SecurityUtils.java
- api/src/main/java/uk/gov/hmcts/payment/api/configuration/security/SpringSecurityConfiguration.java
Clean up
Clean up
```
[ ] Yes
[x] No
```
> remove unused imports and some clean up

- audit.json
> PAY-3432:Nightly Build issue fix

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
Apportionment chart changes
```
[ ] Yes
[x ] No
```
> Apportionment chart changes

- api/src/main/resources/application.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
> PAY:3162C: chart version without IAC

- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
Chart version upgrade for launch darkly implementation.
```
[ ] Yes
[ x] No
```
> Chart version upgrade for launch darkly implementation.

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-3471- FR telephony chart changes.
```
[ ] Yes
[ x] No
```
> PAY-3471 - FR telephony chart changes.

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/RestErrorHandler.java
> Added the sonar quality changes ..

- api/src/main/resources/db/changelog/db.changelog-0.1.4.yaml
- api/src/test/java/uk/gov/hmcts/payment/api/FeePayApportionServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
> adding sonar quality issue fixes

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
Chart changes for PCI PAL antenna
```
[ ] Yes
[ x] No
```
> Chart changes for PCI PAL antenna

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
Publish product chart for a strategic fix
> PAY-3147- publishing product chart for strategic fix changes

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentControllerTest.java
- api/src/test/resources/application-componenttest.properties
Master pipeline is failing due to code coverage is less than 80% (77.4%). Modified conditions to fix issues in some of the classes.
> Code coverage issue fixes on Master

- docker-compose.yml
Docker compose file refactoring for some properties
> PAY-3685- Docker compose file refactoring for some properties

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/RestErrorHandler.java
Code coverage is below 66% percent causing sonar quality check getting failed. We have refactored and fixed the issue with these changes
> PAY-3685- Code Coverage fix

- api/build.gradle
- api/lombok.config
- api/src/main/java/uk/gov/hmcts/payment/api/dto/BulkScanPaymentRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentGroupDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentGroupResponse.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentRecordRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RemissionDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RemissionRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/TelephonyCallbackDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/email/Email.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentReportControllerMockTest.java
- dependency-check-suppressions.xml
> Pay 3641 payment nightly build

- api/build.gradle
- api/lombok.config
- api/src/main/java/uk/gov/hmcts/payment/api/dto/BulkScanPaymentRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentGroupDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentGroupResponse.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentRecordRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RemissionDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RemissionRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/TelephonyCallbackDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/email/Email.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentReportControllerMockTest.java
> Mutation coverage issue fix

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
Removed changes for pci pal antenna , IAC onboarding , FR telephony
> PAY-3147- chart for strategic fix on top of production

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-3719
PAY-3719 Divorce PBA chart changes along with PCI PAL Antenna, FR Telephony and IAC PBA chart changes.
```
[ ] Yes
[x ] No
```
> PAY-3719 Divorce PBA chart changes

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-3721
PAY-3697
1.Move CMC PBA from Config 1 to Config 2
2.Whitelisting UNSPEC CMC service
**This change is for DEMO environment.**
```
[ ] Yes
[x ] No
```
> [[AR]] - PAY-3721,PAY-3697 - Move CMC PBA from Config 1 to Config 2 chart changes and Whitelisting UNSPEC CMC service

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- charts/payment-api/values.preview.template.yaml
NA
PBA pipeline failure fix.
```
[ ] Yes
[x ] No
```
> PBA pipeline failure fix.

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-3471
FR Telephony prod chart changes
```
[ ] Yes
[x ] No
```
> FR Telephony prod chart changes

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/service/PaymentTestService.java
Test Case fix for ITHC Changes.
```
[ ] Yes
[ ] No
```
> Test Case fix for ITHC Changes.

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CardPaymentController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/v1/componenttests/PaymentsComponentTest.java
> Rolling back return url Changes.

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/CreditAccountPaymentRequest.java
- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/util/Service.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/resources/application-local.properties
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CreditAccountPaymentControllerTest.java
- api/src/test/resources/application-componenttest.properties
PAY-3697
Unspec PBA changes
```
[ ] Yes
[x ] No
```
> [[AR]] - PAY-3697 Unspec PBA changes

- api/src/main/resources/application-local.properties
- build.gradle
> Pay 3743 upgraded core case data store client 4.6.4 to 4.7.3

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
NA
IAC PBA chart changes for prod
```
[ ] Yes
[x ] No
```
> IAC PBA chart changes for prod

- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTestConfiguration.java
> TA-151: Extend test scenarios for Divorce

- dependency-check-suppressions.xml
> supression added for CVE-2020-15250

- infrastructure/main.tf
> PAY-3918 : Removed the OLD DB instance mapping from main.tf

- api/build.gradle
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentGroupControllerTest.java
- build.gradle
- dependency-check-suppressions.xml
- reference-data/build.gradle
> change test case to resolve build issue

- api/build.gradle
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentGroupControllerTest.java
- build.gradle
- reference-data/build.gradle
> org.testcontainers:postgresql upgrade to 1.15.1

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/resources/application-local.properties
- model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/MockAccountServiceImpl.java
> Nightly build failure at mutation and functional

- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
- api/src/main/java/uk/gov/hmcts/payment/api/reports/FeesRegisterAdapter.java
- api/src/main/java/uk/gov/hmcts/payment/api/reports/FeesRegisterClient.java
- api/src/main/java/uk/gov/hmcts/payment/api/reports/FeesService.java
- dependency-check-suppressions.xml
PAY-4034
Loggers added.
```
[ ] Yes
[x ] No
```
> [[AR]] - PAY-4034 - Loggers added

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
> PAY-4088: Test case Refactor

- audit.json
> PAY-4117: Manually confirm that the timestamp data is not sensitive

- Jenkinsfile_CNP
- api/build.gradle
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/consumer/ReferenceDataLocationConsumerTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/AccountProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTestConfiguration.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTestConfiguration.java
- api/src/contractTest/resources/application.yml
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/AccountController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/CreditAccountPaymentController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentController.java
- dependency-check-suppressions.xml
> Pay 3900 fix contract tests

- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
> PAY-4179 : Nightly Build issue fix

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CMCCardPaymentPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentBarPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentBulkscanLiberataPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentTelephonyLiberataPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentsSearchFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/dsl/PaymentsTestDsl.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/service/PaymentTestService.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/util/PaymentsDataUtil.java
- dependency-check-suppressions.xml
- model/src/main/java/uk/gov/hmcts/payment/api/service/DelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/LoggingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentOperationsService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRecordServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentService.java
PAY-4088
Creating new pr for PAY-4088 due to memory leak on existing pr
```
[ ] Yes
[x] No
```
> Liberata perf pay 4088

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-4156
Probate PBA chart changes
```
[ ] Yes
[ x] No
```
> [[AR]] - PAY-4156 - Probate PBA chart changes

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> Probate chart changes reverted.

- cve-resolution-strategy.gradle
> CVE fix on Jetty package

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-2296
Adding keyvault secret to read sendgrid api token
```
[ ] Yes
[ x ] No
```
> DTSPO-2296 Reading keyvault secret for sendgrid API token

- api/src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/DTSPO-2296
Adding spring mail password secret alias for sendgrid
```
[ ] Yes
[ x ] No
```
> DTSPO-2296 - Sendgrid migration

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CMCCardPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentBarPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentRecordFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentsSearchFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentsTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/AccountController.java
- cve-resolution-strategy.gradle
> functional test and CVE fix

- dependency-check-suppressions.xml
> Nightly Build issue fix

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/CreditAccountPaymentRequest.java
- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/util/Service.java
- api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/CreditAccountPaymentRequestTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/main/resources/application-local.properties
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CreditAccountPaymentControllerTest.java
- api/src/test/resources/application-componenttest.properties
- model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentAllocation.java
https://tools.hmcts.net/jira/browse/PAY-4469
Changing unpsec service name to CIVIL and whitelist civil_service
```
[ ] Yes
[x] No
```
> Changing unpsec service name to CIVIL and whitelist civil_service

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentsSearchFunctionalTest.java
> Updated utc zone for test

- audit.json
> nightly build fix - 21-05-21

- api/src/main/resources/application.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-4627
Chart changes for whitelisting Civil service in Prod and AAT
```
[ ] Yes
[ x] No
```
> [[AR]] - PAY-4627 - Chart changes for whitelisting Civil service in Prod and AAT.

- cve-resolution-strategy.gradle
> cve fix for nightly build failure

- cve-resolution-strategy.gradle
> Nightly build 24 06 21

- security.sh
> Nightly-dev-security-scan-fix-01-07-21

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
TBC
IAC and Probate backend chart changes for prod.
```
[ ] Yes
[x ] No
```
> IAC and Probate backend chart changes for prod.

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
NA
Reverting IAC and Probate backend chart changes for prod.
```
[ ] Yes
[ x] No
```
> Reverting IAC and Probate backend chart changes for prod.

- cve-resolution-strategy.gradle
NA
CVE fix for CVE-2021-27568
```
[ ] Yes
[x ] No
```
> CVE fix for CVE-2021-27568

- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/AccountProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/AccountController.java
> TA-255: Add provider test for ExUi account interaction

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/reports/PaymentReportType.java
- api/src/main/java/uk/gov/hmcts/payment/api/reports/PaymentsReportService.java
> Report controller -  cmc and finrem to trigger email

- api/src/test/java/uk/gov/hmcts/payment/api/controllers/RemissionControllerTest.java
- charts/payment-api/Chart.yaml
> upgrade helm chart version

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- api/src/main/resources/db/changelog/db.changelog-0.1.7.yaml
- api/src/main/resources/db/changelog/db.changelog-master.xml
PAY-4368
PAY-4368 Bar leeds rollout changes. 
```
[ ] Yes
[ x] No
```
> [[AR]] - PAY-4368 Bar leeds rollout changes.

- api/src/main/java/uk/gov/hmcts/payment/api/dto/RemissionDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentGroupDtoMapper.java
> feeId added in RemissionDto

- api/src/test/java/uk/gov/hmcts/payment/api/controllers/RemissionControllerTest.java
- charts/payment-api/values.preview.template.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/service/RemissionServiceImpl.java
> PAY-5136- Revert retro remission changes

- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
> Change retro code

- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
- charts/payment-api/values.yaml
- docker-compose.yml
> refunds_api whitelisted in payment

- Jenkinsfile_nightly
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- build.gradle
- config/fortify-client.properties
- dependency-check-suppressions.xml
> adding Fortify changes

- cve-resolution-strategy.gradle
> CVE fix CVE-2021-22096

- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
> Removing cpo topic primary send listen shared access key

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainService.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/servicerequest/DeadLetterDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/servicebus/TopicClientService.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java
> dead letter process initial

- api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/servicebus/ServiceRequestDomainServiceTest.java
> test case fix for dead lettter queue

- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> added paymentoutcome_web to values.yaml and application.properties

- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
> Subscription name change

- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTestConfiguration.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTestConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/mapper/ServiceRequestDtoDomainMapper.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CreditAccountPaymentServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/scheduler/FeesServiceTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/exceptions/PaymentServiceNotFoundException.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/DelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/FeesService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/FeesServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/LoggingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/ServiceToTokenMap.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/govpay/GovPayDelegatingPaymentServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/govpay/ServiceToTokenTest.java
> changes added for Service Request GET card payment status

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RemissionFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/mapper/ServiceRequestDomainDataEntityMapper.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/mapper/ServiceRequestDomainDataEntityMapperTest.java
> W2p bug fix

- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/main/resources/liquibase.properties
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/OrderControllerTest.java
- api/src/test/resources/application-componenttest.properties
- docker-compose.yml
> removed the unwanted info

- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/servicebus/ServiceRequestDomainServiceTest.java
> added 500 error

- api/src/main/java/uk/gov/hmcts/payment/api/util/ServiceRequestUtil.java
> Defect fix

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainService.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentReference.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentStatusDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/mapper/PaymentDtoMapperTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/servicebus/ServiceRequestDomainServiceTest.java
> 5238 new payment status dto

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/FeePayApportionController.java
- model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentFeeRepository.java
> Issue 5270

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentsSearchFunctionalTest.java
> build issue fix

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- build.gradle
> log4j upgrade

- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/main/resources/liquibase.properties
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/OrderControllerTest.java
- api/src/test/resources/application-componenttest.properties
- docker-compose.yml
> removed sen info

- build.gradle
> log4j upgrade to 2.16.0

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestBasedOnlineCardPayment.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentDtoMapper.java
> Defect fix3

- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
> message topic test

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/RestTemplateConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/RefundsController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentRefundRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RefundRequestDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RefundResponse.java
- api/src/main/java/uk/gov/hmcts/payment/api/exception/InvalidRefundRequestException.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsService.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRefundsServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/RefundControllerTest.java
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- gov-pay-client/src/main/java/uk/gov/hmcts/payment/api/external/client/dto/RefundPaymentRequest.java
> Payment Refund intiate

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyFunctionalTest.java
> Adding a space to run the PR

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/AccountController.java
> add extra space to trigger build

- api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/CardPaymentRequestTest.java
- api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/CreditAccountPaymentRequestTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/OnlineCardPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/main/resources/bootstrap.yaml
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
> Service on boarding : Adoption

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundRequestorJourneyBulkscanPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyPBAFunctionalTest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/Notification.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/DelegatingPaymentServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentReconciliationComponentTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRefundsServiceTest.java
> Pay 5360 ContactDetails validation 

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestBasedOnlineCardPayment.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
> inconsistentStatusFix

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/FeesController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/OrderController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PBAController.java
Reverts hmcts/ccpay-payment-app#1108
> Revert "Sayali"

- gradlew.bat
Reverts hmcts/ccpay-payment-app#1110
> Revert "change3"

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PBAController.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/PbaControllerTest.java
> Defect fix6

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
> Ignored test

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestBasedOnlineCardPayment.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/dsl/PaymentsTestDsl.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/service/ServiceRequestTestService.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/OnlineCardPaymentRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/servicerequest/ServiceRequestPaymentDto.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java
- build.gradle
- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
> W2p changes

- cve-resolution-strategy.gradle
> cve issue fix-CWE-862

- cve-resolution-strategy.gradle
> cve issue fix

- charts/payment-api/Chart.yaml
> Chart update

- charts/payment-api/Chart.yaml
> chart version update

- api/src/main/resources/bootstrap.yaml
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> Arbab cog patch 1

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/RefundRequestDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java
- build.gradle
- dependency-check-suppressions.xml
…annel and paymentMethod
```
[ ] Yes
[ ] No
```
> PAY-5516 Updated post refund end-points with additional attributes - paymentChannel and paymentMethod

- build.gradle
- dependency-check-suppressions.xml
> cve supress

- api/build.gradle
- build.gradle
- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
> cve fix+suppression date extended

- dependency-check-suppressions.xml
> CVE-2022-22965 -suppressed

- api/src/main/java/uk/gov/hmcts/payment/api/dto/ResubmitRefundRemissionRequest.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRefundsServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/RefundsControllerTest.java
> PAY-5536 Resubmit refund validation logic

- Jenkinsfile_nightly
- dependency-check-suppressions.xml
> Extend cve date to 30/09/2022

- charts/payment-api/Chart.yaml
- dependency-check-suppressions.xml
> CVE-2022-33915 and CVE-2022-34305 has been suppressed.

- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
> Refunds PR pointing

- api/src/main/resources/bootstrap.yaml
- charts/payment-api/Chart.yaml
> chart version update and bootstrap value

- Jenkinsfile_nightly
for smooth functional test execution.
```
[ ] Yes
[ ] No
```
> modify payment-app nightly build time

- dependency-check-suppressions.xml
> Suppressed CVEs

- api/src/main/java/uk/gov/hmcts/payment/api/servicebus/CallbackServiceImpl.java
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
> Merge conflict resolve

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/MaintenanceJobsController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/CardPaymentComponentTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/DelegatingPaymentServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRecordComponentTest.java
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/ServiceToTokenMap.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingCardPaymentLinkServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentServiceTest.java
> Mop up fix

- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
> PAY-5681 Mop up fix

- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
> reverted code fixes for 27 and 28 July 2022

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentRecordFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentTelephonyLiberataPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentsSearchFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentFunctionalTest.java
- charts/payment-api/Chart.yaml
> Pipeline Stability Improvements - FTs

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusController.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRefundsServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/PaymentGroupControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/TelephonyControllerTest.java
- charts/payment-api/values.preview.template.yaml
- cve-resolution-strategy.gradle
- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentServiceImpl.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/UserAwareDelegatingPaymentService.java
> Junit fix after master synch

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/dsl/PaymentsTestDsl.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusController.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateService.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentReconciliationComponentTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusControllerTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentFailureRepository.java
> unpcressed payment update changes

- api/src/functionalTest/resources/application-functional-tests.properties
- catalog-info.yaml
- charts/payment-api/values.preview.template.yaml
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
> adding additional database to payment

- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
> Cve suppressed - CVE-2022-38749, CVE-2022-38750, CVE-2022-38751

- .gitignore
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
> update date in suppression file

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> adding keyvault entries

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PciPalCallbackTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/dsl/PaymentsTestDsl.java
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
> Generated random ccd case number to fix broken FT

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PciPalCallbackTest.java
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
> Pointed to Refunds PR-280

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PciPalCallbackTest.java
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
> PAY-5638 Sonar Critical Fixes

- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/DisputeDTO.java
- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/DisputeDto.java
- api-contract/src/main/java/uk/gov/hmcts/payment/api/contract/PaymentDto.java
- api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/PaymentDtoTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/java/uk/gov/hmcts/payment/api/dto/PaymentGroupDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/mapper/PaymentGroupDtoMapper.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImpl.java
- api/src/main/java/uk/gov/hmcts/payment/api/util/ServiceRequestUtil.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/CaseControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImplTest.java
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
- model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentFailureRepository.java
> service request changes

- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
- cve-resolution-strategy.gradle
- model/build.gradle
> upgrade snake yaml

- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
- docker-compose.yml
> notification app added as trusted for s2s

- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
> updated chart, supressed cve

- .gitignore
- Jenkinsfile_CNP
- Jenkinsfile_nightly
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/config/TestConfigProperties.java
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
> CVE Suppression Date Update

- api/src/functionalTest/resources/application-functional-tests.properties
> bulk scan pointing

- api/src/functionalTest/resources/application-functional-tests.properties
> make http for bulk scanning

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
> Updated DCN generation logic to avoid any conflicts

- api/src/functionalTest/resources/application-functional-tests.properties
> Pointing to AAT urls

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/payment-api/Chart.yaml
> updated deprecated after to afterAlways

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/AccountProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/ServiceRequestProviderTest.java
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
> sync with master

- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
> PACT changes

- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/FeePayApportionController.java
- charts/payment-api/values.preview.template.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/model/PaymentFeeRepository.java
> initialized ArrayList

- api/build.gradle
> publish pact test results true

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/FeePayApportionController.java
- charts/payment-api/values.preview.template.yaml
> added filtering logic in fee-pay-apportion ep

- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/AccountProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/ServiceRequestProviderTest.java
> Added @IgnoreNoPactsToVerify

- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
> suppressing issue pending jackson-core fix

- Jenkinsfile_CNP
- api/build.gradle
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/AccountProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/ServiceRequestProviderTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- build.gradle
- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
> sync up with master

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/PaymentGroupServiceImpl.java
> removed log statement from status endpoint

- api/src/test/java/uk/gov/hmcts/payment/api/componenttests/PaymentRefundsServiceTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/service/PaymentServiceImplTest.java
- model/src/test/java/uk/gov/hmcts/payment/api/util/RefundEligibilityUtilTest.java
> Fix coverrage v1

- README.md
- api/src/main/java/uk/gov/hmcts/payment/api/domain/mapper/ServiceRequestDomainDataEntityMapper.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
> Apportion changes

- audit.json
- functional-output/README.md
https://tools.hmcts.net/jira/browse/PAY-4884
Fix for running ZAP tests.
```
[ ] Yes
[x] No
```
> PAY-4884 Fix security issues.

- api/src/functionalTest/resources/application-functional-tests.properties
> pointing to aat

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyPBAFunctionalTest.java
> pba account change

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-4884
Suppression for CVE with no fix available.
```
[ ] Yes
[x] No
```
> Suppression for cve with no fix available.

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/resources/application-functional-tests.properties
- audit.json
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- scripts/config.sh
https://tools.hmcts.net/jira/browse/PAY-5997
Update to use platform.hmcts.net for staging and preview URLs.
```
[ ] Yes
[x] No
```
> PAY-5997: Update references to use platform.hmcts.net

- dependency-check-suppressions.xml
> fixing CVES

- api/build.gradle
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
> PAY-6040-CVE-fixes

- api/build.gradle
- build.gradle
- case-payment-orders-client/build.gradle
- model/build.gradle
- otp/build.gradle
> Fix broken dependencies (non-breaking as possible!)

- Jenkinsfile_CNP
- api/src/functionalTest/resources/application-functional-tests.properties
- build.gradle
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- dependency-check-suppressions.xml
Remove need to raise separate PRs on dependent F&P apps
```
[ ] Yes
[x] No
```
> Reduce reliance on other PRs for Preview builds

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/AccountFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BulkscanPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CMCCardPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/OnlineCardPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAAccountsFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentBulkscanPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentGroupFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentTelephonyLiberataPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundRequestorJourneyBulkscanPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyPBAFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RemissionFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentsTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/config/TestConfigProperties.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-6001
```
[ ] Yes
[X] No
```
> fix skipped tests

- Jenkinsfile_CNP
- api/src/functionalTest/resources/application-functional-tests.properties
- charts/payment-api/values.preview.template.yaml
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6406
Suppressing CVE-2023-34036, removing PR pointing so it picks up internal apps in Preview.
```
[ ] Yes
[x] No
```
> PAY-6406: Update to suppress CVE-2023-34036

- api/liquibase.gradle
> fixing liquibase

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
https://tools.hmcts.net/jira/browse/PAY-6391
Removed redundant secret.
```
[ ] Yes
[x] No
```
> PAY-6391: Remove redundant secret.

- api/build.gradle
- charts/payment-api/values.preview.template.yaml
"info.solidsoft.pitest" version '1.9.0' latest version
> Nightly dev

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6443
Add CVE fix and suppression.
```
[ ] Yes
[x] No
```
> PAY-6443: Add CVE resolution and suppression

- charts/payment-api/Chart.yaml
Not applicable
Refresh app to pick up updated pci pal secrets, use latest charts for refunds and update prod image which is out of sync.
```
[ ] Yes
[x] No
```
> Fix out of date image in Prod.

- dependency-check-suppressions.xml
PAY_6475
CVE-2020-8908 fix
```
[ ] Yes
[ x ] No
```
> CVE-2020-8908 fix

- dependency-check-suppressions.xml
PAY_6523
CVE-2023-41080 Surpression fix
```
[ ] Yes
[ x ] No
```
> CVE-2023-41080 Surpression fix

- api/build.gradle
- dependency-check-suppressions.xml
PAY_6557
Revert to previous version in build.gradle file
```
[ ] Yes
[ x ] No
```
> version reversion

- .github/renovate.json
PAY-6543: Payments API Renovate Update Backend
[PAY-6543] (https://tools.hmcts.net/jira/browse/PAY-6543).
> PAY-6543: Payments API Renovate Update Backend

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/AccountFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BarPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/BulkscanPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CMCCardPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/CallBackServiceFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/OnlineCardPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAAccountsFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PBAPaymentPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentAmountTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentBulkscanPerformanceLiberataTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentGroupFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentRecordFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentTelephonyLiberataPerformanceTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentsSearchFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PciPalCallbackTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundRequestorJourneyBulkscanPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyPBAFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyTelephonyPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RemissionFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestBasedOnlineCardPayment.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestFunctionalTests.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/ServiceRequestPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentsTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/fixture/PaymentFixture.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/idam/IdamApi.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/idam/IdamService.java
https://tools.hmcts.net/jira/browse/PAY-5991
> refactor FTs to cleanup the test data

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
> PAY-6573_secretsChange

- charts/payment-api/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-6571
> PAY-6571: Update Charts Refunds Version

- api/src/main/resources/application.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
PAY-6643: Add nfdiv-case-api to gov pay keys #1525
[PAY-6643] (https://tools.hmcts.net/jira/browse/PAY-6643).
>  PAY-6643: Add nfdiv-case-api to gov pay keys #1525

- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6682
Creation of SDP user via terraform
> PAY-6682_sdp user creation

- charts/payment-api/Chart.yaml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6701
Force access to flexible server db
> PAY-6701 Force Access to flexible db

- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6702
Amend SDP user acess
> PAY-6702 Amend SDP user access

- dependency-check-suppressions.xml
PAY-6702
Amend suppression dates
> PAY-6702 Amend suppression date

- api/build.gradle
- dependency-check-suppressions.xml
- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6723
Update to make SDP user module work for all environments.
> PAY-6723: Fix SDP Config in ITHC and PerfTest

- infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6723
Update to exclude logic for SDP user creation in perftest and ithc.
> Pay 6723 final sdp fix

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6741
remove old references to logback
> PAY-6746 remove old references to logback

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6659
Decommission v11 payments database
> PAY-6659 decommission v11 database

- api/src/main/java/uk/gov/hmcts/payment/api/reports/PaymentReportType.java
https://tools.hmcts.net/jira/browse/PAY-6803
Adding Damages PaymentReportType.
> PAY-6803: Adding new PaymentReportType

- README.md
PAY-6838v2
Push master into nightly dev for 30/01/24
- [ x ] Does this PR introduce a breaking change
> PAY-6838v2

- README.md
PAY-6838v3
Pull master into nightly dev
- [ x ] commit messages are meaningful and follow good commit message guidelines
- [ x ] Does this PR introduce a breaking change
> PAY-6838v3

- dependency-check-suppressions.xml
PAY-6838v4
Surpressions fix
- [ x ] commit messages are meaningful and follow good commit message guidelines
- [ x ] Does this PR introduce a breaking change
> PAY_6838v4

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/IdempotencyServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/domain/service/IdempotencyServiceImplTest.java
https://tools.hmcts.net/jira/browse/PAY-6586
To make code more robost for Librata outages.
> PAY-6580-PBA_payment_additional_retry

- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentRefundsServiceImpl.java
Reverts hmcts/ccpay-payment-app#1569
> Revert " PAY-5918: Restriction on Refund CREATION due to a Remission (Upfront…"

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6881
addressed CVE-2023-34042
> PAY-6881-cve-2023-34042

- dependency-check-suppressions.xml
PAY-6911: Pipeline analysis and resolution 26 February 2023
[PAY-6911] (https://tools.hmcts.net/jira/browse/PAY-6911).
> PAY-6911: Pipeline analysis and resolution 26 February 2023

- api/src/main/resources/db/changelog/db.changelog-0.1.12.yaml
- api/src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/PAY-6958
Adding missing indexes after investigations into performance on the Payment DB.
> PAY-6958: Adding indexes to improve performance

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6972
address CVE CVE-2024-26308
> PAY-6972_CVE-2024-26308

- api/src/main/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceImpl.java
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
https://tools.hmcts.net/jira/browse/PAY-5797
Testing changes pointing to new service-bus
> PAY-5797: Update to point to new service-bus.

- .github/workflows/stale.yml
https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Addition of stale.yml for PR auto close bot 
- [ x ] Does this PR introduce a breaking change
>  PAY-6982 Addition of stale.yml for PR auto close bot 

- api/build.gradle
- api/src/main/java/uk/gov/hmcts/PaymentApiApplication.java
- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6115
https://tools.hmcts.net/jira/browse/PAY-6104
https://tools.hmcts.net/jira/browse/PAY-6107
> PAY-6115/PAY-6104/PAY-6107: Fix CVE-2022-1471/CVE-2022-0839/CVE-2022-42889

- README.md
- cve-resolution-strategy.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-7124
Address High Vulnerabilities
> PAY-7124: Address High Vulnerabilities

- api/build.gradle
Affects deployment of PAY-7141
Reverting Renovate update as it's causing a build issue.
> Update to revert renovate change.

- api/build.gradle
- api/src/functionalTest/resources/application-functional-tests.properties
- api/src/main/resources/application-local.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-componenttest.properties
- charts/payment-api/Chart.yaml
- charts/payment-api/values.preview.template.yaml
- charts/payment-api/values.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/service/PciPalPaymentService.java
https://tools.hmcts.net/jira/browse/PAY-6433
Update IAC Telephony Flow Id
> PAY-6433: IAC Telephony Flow Id Update

- api/build.gradle
- build.gradle
https://tools.hmcts.net/jira/browse/PAY-7212
Removed properties-volume-spring-boot-starter
> PAY-7212: Remove properties-volume-spring-boot-starter

- api/src/main/resources/db/changelog/db.changelog-0.1.14.yaml
- api/src/main/resources/db/changelog/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/PAY-7265
Updating refund fees to have a positive volume of 1 if null or 0.
> Pay 7265 refund 500 fix 2

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/PaymentStatusFunctionalTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/TelephonyPaymentsTest.java
- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/service/PaymentTestService.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusController.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/TelephonyPaymentsReportDto.java
- api/src/main/java/uk/gov/hmcts/payment/api/dto/TelephonyPaymentsReportResponse.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateService.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/dto/TelephonyPaymentsReportDtoTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/service/CustomTupleForTelephonyPaymentsReport.java
- api/src/test/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImplTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/model/Payment2Repository.java
- model/src/test/java/uk/gov/hmcts/payment/api/model/CustomTuple.java
- model/src/test/java/uk/gov/hmcts/payment/api/model/Payment2RepositoryTest.java
See [PAY-7286](https://tools.hmcts.net/jira/browse/PAY-7286)
New created Telephony Payments Report
Created json locally with teh write format for the report to be handled in the frontend.
> PAY-7286-backend telephonyPaymentsReport

- charts/payment-api/Chart.yaml
- charts/payment-api/values.yaml
- model/src/main/java/uk/gov/hmcts/payment/api/service/govpay/ServiceToTokenMap.java
https://tools.hmcts.net/jira/browse/PAY-7374
Add the missing civil service for card-payments.
> PAY-7374: Update Service Map for Civil Service

- api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
https://tools.hmcts.net/jira/browse/PAY-7425
the mock data was not matching.
this didn't matter originally, but more checking on reference numbers have been done since, which broke the test.
provider test passes now
> PAY-7245 make sure reference in response matches request

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/SwaggerConfiguration.java
- api/src/main/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImpl.java
- api/src/test/java/uk/gov/hmcts/payment/api/service/PaymentStatusUpdateServiceImplTest.java
Reverts hmcts/ccpay-payment-app#1699
> Revert "Pay 7452"

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusController.java
- api/src/main/java/uk/gov/hmcts/payment/api/controllers/ServiceRequestController.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/PaymentStatusControllerTest.java
https://tools.hmcts.net/jira/browse/PAY-7443
Improve code coverage - see https://github.com/hmcts/ccpay-payment-app/pull/1698 for original changes.
See https://github.com/hmcts/ccpay-payment-app/pull/1698.
> Pay 7443 improve code coverage

- api/src/main/java/uk/gov/hmcts/payment/api/configuration/security/SpringSecurityConfiguration.java
https://tools.hmcts.net/jira/browse/PAY-7485
Remove antMatchers and replace with requestMatchers.
Functional tests should be enough for this change.
> PAY-7485: Update to improve SonarQube Maintainability Quality Score

- Jenkinsfile_CNP
See [PAY-7213](https://tools.hmcts.net/jira/browse/PAY-7213)
fix env vars so that contracts are found on the pact broker
local testing
> PAY-7213 PACT contract verification

- api/src/main/java/uk/gov/hmcts/payment/api/controllers/AccountController.java
- api/src/test/java/uk/gov/hmcts/payment/api/controllers/AccountControllerTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/domain/service/ServiceRequestDomainServiceTest.java
- api/src/test/java/uk/gov/hmcts/payment/api/service/AccountServiceTest.java
- model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
https://tools.hmcts.net/jira/browse/CME-24
Fix functional test related to AccountService.
Functional tests passing.
> CME-24: Fix functional tests

- api/build.gradle
- api/pacts/payment_App-referenceData_location.json
https://tools.hmcts.net/jira/browse/PAY-7522
Revert version of pact library.
Pipeline green.
> PAY-7522: Update to fix pact tests

- charts/payment-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-382
Update OCI endpoints
> CME-382: OCI changes

- build.gradle
- cve-resolution-strategy.gradle
See [PAY-7740](https://tools.hmcts.net/jira/browse/PAY-7440
Upgrades related to CVEs
Tested as part of pipeline
> PAY-7740 Pipeline fixes

- infrastructure/cft-api-mgmt-logging.tf
https://tools.hmcts.net/jira/browse/PAY-7820
Add APIM logging for the Payment App.
Tested in DEMO.
> PAY-7820: Update APIM logging for the payment-api

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-126
Added action group to alert about high database usage.
> CME-126 add db monitoring action group

- api/build.gradle
- api/src/main/java/uk/gov/hmcts/payment/api/configuration/RestTemplateConfiguration.java
- build.gradle
- jitpack.yml
- model/build.gradle
https://tools.hmcts.net/jira/browse/CME-529
Replace jitpack with azure artifactory
> CME-529 replace jitpack with azure artifactory

- infrastructure/cft-api-mgmt.tf
- infrastructure/template/cft-api-policy.xml
https://tools.hmcts.net/jira/browse/PAY-7850
Refactor the APIM policy template to call the s2s client secret from a named values list.
Manual testing in DEMO.
Resolved ussue found in Github for BulkScanning API.
> PAY-7850: Update APIM Policy to use named values

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7984
commons-lang cve
pipeline
> PAY-7984 commons-lang3 cve

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7984
tomcat upgrade due to cve
> PAY-7984 tomcat cve

- api/src/main/resources/application.properties
Add missing HikariCP configuration properties with environment variable fallbacks to optimize database connection handling
https://tools.hmcts.net/jira/browse/CME-209
> CME-209: fix(db): configure HikariCP connection pool settings

- cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-8028
cve
> Pay 8028 pipeline fixes

- cve-resolution-strategy.gradle
PAY-8087: Pipeline fixes - week beginning 15 of  March 2025
[PAY-8087] (https://tools.hmcts.net/jira/browse/PAY-8087).
>  PAY-8087: Pipeline fixes - week beginning 15 of  March 2025

- api/build.gradle
See https://tools.hmcts.net/jira/browse/PAY-8104
reverting pact version from renovate
built project
> PAY-8104 revert pact version

- api/src/functionalTest/java/uk/gov/hmcts/payment/functional/RefundsRequestorJourneyPBAFunctionalTest.java
https://tools.hmcts.net/jira/browse/PAY-7759
> PAY-7759: Disable Test

- api-contract/src/test/java/uk/gov/hmcts/payment/api/contract/TelephonyCardPaymentsRequestTest.java
https://tools.hmcts.net/jira/browse/PAY-7758
Contract test output updated after code change.
> PAY-7759: Fixing contract test
